[package]
name = "icos-phere"
version = "0.1.0"
edition = "2021"
authors = ["Vladyslav Stepanov <wrottkitkatt@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
sdl2 = "0.35.1"
